In [1]:
import numpy as np

In [2]:
A = np.array([0.52, 0.8, 0.95, 0.29, 0.76])

In [3]:
A

array([0.52, 0.8 , 0.95, 0.29, 0.76])

In [4]:
B = np.array([0.39, 0.74, 0.26, 0.5, 0.32])

In [5]:
B

array([0.39, 0.74, 0.26, 0.5 , 0.32])

In [6]:
A + B

array([0.91, 1.54, 1.21, 0.79, 1.08])

In [7]:
! pip3 install git+https://github.com/pykeen/pykeen.git
pykeen.env()

  Cloning https://github.com/pykeen/pykeen.git to /private/var/folders/xm/lz8thrrs1l5cks282q243ty40000gn/T/pip-req-build-xfhtittx
  Running command git clone --filter=blob:none --quiet https://github.com/pykeen/pykeen.git /private/var/folders/xm/lz8thrrs1l5cks282q243ty40000gn/T/pip-req-build-xfhtittx
  Resolved https://github.com/pykeen/pykeen.git to commit cb226fc1ff946f0bc6c1296ea5d3ee87a4ef773b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 4.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.2/54.2 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 365.7/365.7 kB 6.9 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

NameError: name 'pykeen' is not defined